version: '3.8'

services:
  casepack-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    image: casepack-optimizer:latest
    container_name: casepack-optimizer-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - casepack-network

networks:
  casepack-network:
    driver: bridge