services:
  - type: web
    name: casepack-optimizer
    runtime: docker
    repo: https://github.com/shubamchaudhary/Casepack-Optimiser
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75.0
      - key: SERVER_PORT
        value: 8080